# Local development environment
---
version: '3.7'
services:
  ruby:
    build:
      context: .
      dockerfile: development.docker
    volumes:
      - code:/usr/src/app:nocopy

  solargraph:
    build:
      context: .
      dockerfile: development.docker
    working_dir: $PWD
    environment:
      GEM_PATH: $PWD/vendor/bundle/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
      PATH: $PWD/vendor/bundle/ruby/2.7.0/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command: solargraph socket --host 0.0.0.0 --port 7658
    volumes:
      - code:$PWD:nocopy
    ports:
      - 7658:7658

volumes:
  code:
